#!/usr/bin/env bash
# -----------------------------------------------------------------------------
# Lock the resolved Compose inputs to .env.lock.
#
# The lock file records both image references and build arguments. Tags are
# still tags; use image digests for a fully immutable CI lock.
# -----------------------------------------------------------------------------

set -euo pipefail

LOCK_FILE="${1:-.env.lock}"
PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$PROJECT_ROOT"

command -v docker >/dev/null 2>&1 || { echo "docker is required" >&2; exit 1; }
docker compose version >/dev/null 2>&1 || { echo "docker compose v2 is required" >&2; exit 1; }
command -v jq >/dev/null 2>&1 || { echo "jq is required to write the lock file" >&2; exit 1; }

COMPOSE_FILES=(
  -f docker-compose.yml
  -f compose/db.yml
  -f compose/cache.yml
  -f compose/registry.yml
  -f compose/mq.yml
  -f compose/observability.yml
  -f compose/storage.yml
  -f compose/ci.yml
  -f compose/gateway.yml
  -f compose/docs.yml
)

ALL_PROFILES=$(grep -hoE 'profiles:[[:space:]]*\[[^]]+\]' compose/*.yml 2>/dev/null \
  | grep -oE '"[^"]+"' \
  | tr -d '"' \
  | sort -u \
  | paste -sd, -)

CONFIG_JSON=$(COMPOSE_PROFILES="$ALL_PROFILES" docker compose "${COMPOSE_FILES[@]}" config --format json)

{
  echo "# Auto-generated by scripts/lock-versions.sh on $(date '+%Y-%m-%d %H:%M:%S %Z')"
  echo "# Records all profile-resolved image references and build arguments."
  echo "# Tags are mutable; use image digests for a fully immutable CI lock."
  echo
  echo "[images]"
  printf '%s\n' "$CONFIG_JSON" | jq -r '
    .services
    | to_entries[]
    | select(.value.image != null)
    | "\(.key)=\(.value.image)"
  '
  echo
  echo "[build-args]"
  printf '%s\n' "$CONFIG_JSON" | jq -r '
    .services
    | to_entries[]
    | select(.value.build.args != null)
    | .key as $service
    | .value.build.args
    | to_entries[]
    | "\($service).\(.key)=\(.value)"
  '
} > "$LOCK_FILE"

IMAGE_COUNT=$(sed -n '/^\[images\]$/,/^\[build-args\]$/p' "$LOCK_FILE" | grep -c '=' || true)
ARG_COUNT=$(sed -n '/^\[build-args\]$/,$p' "$LOCK_FILE" | grep -c '=' || true)
echo "Locked ${IMAGE_COUNT} image references and ${ARG_COUNT} build arguments to ${LOCK_FILE}"
