#!/usr/bin/env bash
#--------------------------------------------------------------------------
# Lock compose-resolved image versions to .env.lock
#--------------------------------------------------------------------------
# Captures the EXACT image:tag that `docker compose config` resolves to
# given the current .env. Useful for reproducibility: commit .env.lock
# to git to record what the dev environment was using at this point.
#
# Usage:
#   make lock            # writes to .env.lock (default)
#   ./scripts/lock-versions.sh .env.production
#--------------------------------------------------------------------------

set -euo pipefail

LOCK_FILE="${1:-.env.lock}"
PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

cd "$PROJECT_ROOT"

if ! command -v docker >/dev/null 2>&1; then
  echo "❌ docker is required" >&2
  exit 1
fi

if ! docker compose version >/dev/null 2>&1; then
  echo "❌ docker compose v2 is required" >&2
  exit 1
fi

# Load .env so substitution is correct
if [[ ! -f .env ]]; then
  echo "❌ .env not found in $PROJECT_ROOT. Run 'make init' first." >&2
  exit 1
fi
set -a
# shellcheck disable=SC1091
source .env
set +a

# Collect every image:tag referenced anywhere in the compose project.
#
# `docker compose config --images` only shows services selected by active
# profiles. We don't know in advance which profiles the user might enable,
# so we just grep all compose files for `image:` references and resolve the
# env vars ourselves.

IMAGES_RAW=$(grep -rhE '^[[:space:]]*image:' docker-compose.yml compose/ 2>/dev/null \
  | awk -F'image:' '{print $2}' \
  | sed -E "s/^[[:space:]]+//; s/[\"']//g" \
  | sort -u)

# Substitute env-var references like ${FOO} or $FOO with values from .env
resolve_env() {
  local s="$1"
  while [[ "$s" =~ \$\{([A-Z_][A-Z0-9_]*)\} ]] || [[ "$s" =~ \$([A-Z_][A-Z0-9_]*) ]]; do
    local name="${BASH_REMATCH[1]:-${BASH_REMATCH[0]#\${}}"
    name="${name%\}}"
    local val="${!name:-}"
    s="${s//\$\{$name\}/$val}"
    s="${s//\$$name/$val}"
  done
  echo "$s"
}

IMAGES=""
while IFS= read -r line; do
  [[ -z "$line" || "$line" =~ ^# ]] && continue
  resolved=$(resolve_env "$line")
  IMAGES+="$resolved"$'\n'
done <<< "$IMAGES_RAW"
IMAGES=$(echo "$IMAGES" | sort -u | sed '/^$/d')
COUNT=$(echo "$IMAGES" | grep -c . || true)

if [[ "$COUNT" -eq 0 ]]; then
  echo "❌ No images resolved. Check your .env and compose files." >&2
  exit 1
fi

{
  echo "# Auto-generated by scripts/lock-versions.sh on $(date '+%Y-%m-%d %H:%M:%S %Z')"
  echo "# Source: docker compose config --images (with current .env)"
  echo "# To restore these versions, copy desired IMAGE:TAG values into .env"
  echo ""
  echo "$IMAGES"
} > "$LOCK_FILE"

echo "✓ Locked $COUNT images to $LOCK_FILE"
echo ""
echo "Sample:"
echo "$IMAGES" | head -5 | sed 's/^/  /'
