#!/usr/bin/env bash
# Detect a project's language stack and emit a .mise.toml when none exists.
#
# Invoked explicitly by init-project or by the opt-in zsh chpwd hook.
# Exits 0 in all cases — a silent no-op when the project is already configured
# or no recognisable project files are present.
#
# Recognised files → default tool version (overrides live in
# scripts/languages.defaults, sourced below):
#   package.json       → node    (engines.node wins when parseable)
#   go.mod             → go      (`go ` directive wins, else defaults.go)
#   Cargo.toml         → rust    (rust-version wins, else defaults.rust)
#   composer.json      → php     (require.php wins, else defaults.php)
#   pyproject.toml     → python  (requires-python wins, else defaults.python)
#   requirements.txt   → python  (defaults.python — no version pinning possible)
#
# Usage: detect-stack [dir]  (default: .)

set -u
set -o pipefail

# Single source of truth for default language versions — see the file for
# the rationale. Fail closed (script errors out) if it's missing rather
# than silently using unset defaults.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=./languages.defaults
. "$SCRIPT_DIR/languages.defaults"
. "$SCRIPT_DIR/stack-detection.lib.sh"

target="${1:-.}"
if ! cd "$target" 2>/dev/null; then
  echo "[detect-stack] cannot cd to $target" >&2
  exit 0
fi

# Already configured — leave the project owner's config alone.
if [ -f .mise.toml ] || [ -f .tool-versions ]; then
  exit 0
fi

# Need at least one recognised project file, otherwise we'd be guessing.
has_project_file=0
for f in package.json go.mod Cargo.toml composer.json pyproject.toml requirements.txt; do
  [ -f "$f" ] && has_project_file=1 && break
done
[ "$has_project_file" -eq 0 ] && exit 0

detect_project_stack

[ "${#detected_tools[@]}" -eq 0 ] && exit 0

# --- emit -------------------------------------------------------------------
out=".mise.toml"
{
  printf '# Generated by detect-stack.sh on %s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  printf '# Safe to edit and commit. To suppress auto-detection, set\n'
  printf '#   MISED_SKIP_DETECT=1\n'
  printf '# in the workspace shell or delete this file.\n'
  printf '[tools]\n'
  for i in "${!detected_tools[@]}"; do
    printf '%s = "%s"\n' "${detected_tools[$i]}" "${detected_versions[$i]}"
  done
} > "$out"

printf '[detect-stack] generated %s:\n' "$out"
cat "$out"

# Gated install: only auto-install when the user has explicitly opted in via
# MISE_AUTO_INSTALL=true. Default in the workspace image is `false` because
# casually `cd`-ing into a Rust project while writing Go (or vice versa)
# would otherwise trigger a download you didn't ask for. For migration
# scenarios (cloning a fresh repo, environment bootstrap), flip the var
# on for the session:
#
#   export MISE_AUTO_INSTALL=true   # then `cd` around and tools land on demand
#
# mise's own auto-install behaviour is the same switch — gating this call
# to the same env var keeps "what runs install" in one place.
if [ "${MISE_AUTO_INSTALL:-false}" = "true" ] && command -v mise >/dev/null 2>&1; then
  mise install --quiet 2>/dev/null || true
fi
