#!/usr/bin/env bash
# Detect a project's language stack and emit a .mise.toml when none exists.
#
# Invoked automatically by the zsh chpwd hook installed in base.Dockerfile.
# Exits 0 in all cases — a silent no-op when the project is already configured
# or no recognisable project files are present.
#
# Recognised files → default tool version:
#   package.json       → node  = "22"   (engines.node wins when present and parseable)
#   go.mod             → go    = <version from `go ` directive, else "1.23">
#   Cargo.toml         → rust  = "stable"  (rust-version wins when present)
#   composer.json      → php   = "8.3"   (require.php wins when present)
#   pyproject.toml     → python = "3.12"  (requires-python wins when present)
#   requirements.txt   → python = "3.12"  (no version pinning possible)
#
# Usage: detect-stack [dir]  (default: .)

set -u
set -o pipefail

target="${1:-.}"
if ! cd "$target" 2>/dev/null; then
  echo "[detect-stack] cannot cd to $target" >&2
  exit 0
fi

# Already configured — leave the project owner's config alone.
if [ -f .mise.toml ] || [ -f .tool-versions ]; then
  exit 0
fi

# Need at least one recognised project file, otherwise we'd be guessing.
has_project_file=0
for f in package.json go.mod Cargo.toml composer.json pyproject.toml requirements.txt; do
  [ -f "$f" ] && has_project_file=1 && break
done
[ "$has_project_file" -eq 0 ] && exit 0

# Parallel arrays (portable across bash 3.2 / 4 / 5 — the workspace container
# has bash 5, but keeping it portable lets the host run it for testing).
detected_tools=()
detected_versions=()

# --- node -------------------------------------------------------------------
if [ -f package.json ]; then
  node_ver=""
  if command -v jq >/dev/null 2>&1; then
    raw=$(jq -r '.engines.node // empty' package.json 2>/dev/null || true)
    if [ -n "$raw" ] && [ "$raw" != "null" ]; then
      # Strip range specifiers (^ ~ >= <=) and take the leading x.y as a
      # major.minor fallback. mise accepts `20` as a major-only pin.
      cleaned=$(printf '%s' "$raw" | tr -d '"' | sed -E 's/[\^~><= ]//g')
      node_ver=$(printf '%s' "$cleaned" | grep -Eo '^[0-9]+(\.[0-9]+)?' | head -n1)
    fi
  fi
  detected_tools+=("node")
  detected_versions+=("${node_ver:-22}")
fi

# --- go ---------------------------------------------------------------------
if [ -f go.mod ]; then
  go_ver=$(awk '/^go[[:space:]]/{print $2; exit}' go.mod 2>/dev/null)
  detected_tools+=("go")
  detected_versions+=("${go_ver:-1.23}")
fi

# --- rust -------------------------------------------------------------------
if [ -f Cargo.toml ]; then
  rust_ver=""
  if grep -qE '^[[:space:]]*rust-version' Cargo.toml 2>/dev/null; then
    rust_ver=$(awk -F'"' '/^[[:space:]]*rust-version/ {print $2; exit}' Cargo.toml 2>/dev/null)
  fi
  detected_tools+=("rust")
  detected_versions+=("${rust_ver:-stable}")
fi

# --- php --------------------------------------------------------------------
if [ -f composer.json ]; then
  php_ver=""
  if command -v jq >/dev/null 2>&1; then
    raw=$(jq -r '.require.php // empty' composer.json 2>/dev/null || true)
    if [ -n "$raw" ] && [ "$raw" != "null" ]; then
      php_ver=$(printf '%s' "$raw" | tr -d '"' | sed -E 's/[\^~><= ]//g' | grep -Eo '^[0-9]+(\.[0-9]+)?' | head -n1)
    fi
  fi
  detected_tools+=("php")
  detected_versions+=("${php_ver:-8.3}")
fi

# --- python -----------------------------------------------------------------
if [ -f pyproject.toml ] || [ -f requirements.txt ]; then
  py_ver=""
  if [ -f pyproject.toml ]; then
    raw=$(awk -F'"' '/requires-python/ {print $2; exit}' pyproject.toml 2>/dev/null)
    if [ -n "$raw" ]; then
      py_ver=$(printf '%s' "$raw" | sed -E 's/[<>=~^ ]//g' | grep -Eo '^[0-9]+(\.[0-9]+)?' | head -n1)
    fi
  fi
  detected_tools+=("python")
  detected_versions+=("${py_ver:-3.12}")
fi

[ "${#detected_tools[@]}" -eq 0 ] && exit 0

# --- emit -------------------------------------------------------------------
out=".mise.toml"
{
  printf '# Generated by detect-stack.sh on %s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  printf '# Safe to edit and commit. To suppress auto-detection, set\n'
  printf '#   MISED_SKIP_DETECT=1\n'
  printf '# in the workspace shell or delete this file.\n'
  printf '[tools]\n'
  for i in "${!detected_tools[@]}"; do
    printf '%s = "%s"\n' "${detected_tools[$i]}" "${detected_versions[$i]}"
  done
} > "$out"

printf '[detect-stack] generated %s:\n' "$out"
cat "$out"

# Kick mise so the freshly-written file is picked up on the current shell.
# `MISE_AUTO_INSTALL=true` makes this non-blocking for already-installed
# versions and lazy for new ones.
if command -v mise >/dev/null 2>&1; then
  mise install --quiet 2>/dev/null || true
fi
