#!/usr/bin/env bash
# Interactive project initializer: detect stack, let the user confirm or
# override, then write .mise.toml. Use this when detect-stack.sh's silent
# guess isn't enough (e.g. you want a different version, or you need to
# pin a tool that isn't represented by a recognised project file).
#
# Usage: init-project [dir]  (default: .)

set -u
set -o pipefail

# Default language versions live in ./languages.defaults — same file
# detect-stack.sh sources. Single source of truth.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=./languages.defaults
. "$SCRIPT_DIR/languages.defaults"
. "$SCRIPT_DIR/stack-detection.lib.sh"

target="${1:-.}"
if ! cd "$target" 2>/dev/null; then
  echo "✗ cannot cd to $target" >&2
  exit 1
fi

if [ -f .mise.toml ] || [ -f .tool-versions ]; then
  printf '\033[33m⚠\033[0m  %s already has mise config — refusing to overwrite.\n' "$(pwd)"
  printf '   Remove the existing file first if you really want to re-init.\n'
  exit 1
fi

detect_project_stack
tool_order=("${detected_tools[@]}")
tool_version=("${detected_versions[@]}")

# --- display + confirm ----------------------------------------------------
printf '\n  Project: \033[1m%s\033[0m\n\n' "$(pwd)"

if [ "${#tool_order[@]}" -eq 0 ]; then
  printf '  No project files detected — you'\''ll need to add a tool by hand.\n\n'
else
  printf '  Detected from project files:\n'
  for i in "${!tool_order[@]}"; do
    printf '    • \033[36m%s\033[0m = \033[33m%s\033[0m\n' "${tool_order[$i]}" "${tool_version[$i]}"
  done
  printf '\n'
fi

# Collect final selection. Use plain array indexing rather than associative
# arrays for bash 3.2 portability (lets the host run it for testing too).
final_tools=()
final_versions=()

# Confirm / override / drop each detected tool
for i in "${!tool_order[@]}"; do
  tool="${tool_order[$i]}"
  default="${tool_version[$i]}"
  printf '  include \033[36m%s\033[0m at version [\033[33m%s\033[0m]? ' "$tool" "$default"
  printf '(Y/n/custom-version): '
  read -r ans
  case "$ans" in
    ""|[Yy]|[Yy][Ee][Ss])
      final_tools+=("$tool")
      final_versions+=("$default")
      ;;
    [Nn]|[Nn][Oo])
      ;;
    *)
      final_tools+=("$tool")
      final_versions+=("$ans")
      ;;
  esac
done

# Optional extras — anything mise supports (ruby, java, deno, bun, ...).
while :; do
  printf '\n  add another tool? (e.g. "ruby 3.3", or press enter to finish): '
  read -r ans
  [ -z "$ans" ] && break
  extra_tool=$(printf '%s' "$ans" | awk '{print $1}')
  extra_ver=$(printf '%s' "$ans" | awk '{print $2}')
  if [ -z "$extra_tool" ] || [ -z "$extra_ver" ]; then
    printf '  \033[31m✗\033[0m expected "<tool> <version>"\n'
    continue
  fi
  final_tools+=("$extra_tool")
  final_versions+=("$extra_ver")
  printf '  + \033[36m%s\033[0m = \033[33m%s\033[0m\n' "$extra_tool" "$extra_ver"
done

if [ "${#final_tools[@]}" -eq 0 ]; then
  printf '\n  nothing selected, aborting without writing.\n'
  exit 0
fi

# --- write ----------------------------------------------------------------
out=".mise.toml"
{
  printf '# Generated by init-project.sh on %s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  printf '# Safe to edit and commit.\n'
  printf '[tools]\n'
  for i in "${!final_tools[@]}"; do
    printf '%s = "%s"\n' "${final_tools[$i]}" "${final_versions[$i]}"
  done
} > "$out"

printf '\n  \033[32m✓\033[0m wrote %s:\n\n' "$out"
sed 's/^/    /' "$out"
printf '\n  run \033[1mmise install\033[0m to install the toolchain.\n'
